export const Red = '#ef476f'
export const Yellow = '#ffd166'
export const Green = '#06d6a0'
export const MediumBlue = '#118ab2'
export const DarkBlue = '#073b4c'
export const MediumGray = '#aeaeae'
export const White = '#ffffff'
export const Black = '#353535'